name: Tests

on:
  push:
    paths-ignore:
      - "*.md"
      - "assets/**"
      - "*.yml"
    branches: [main, v3-dev]
  pull_request:
    paths-ignore:
      - "*.md"
      - "assets/**"
      - "*.yml"
    branches: [main, v3-dev]

jobs:
  test-check-colorscheme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux

      - name: Run check colorscheme tests
        run: bash tests/test_check_colorscheme.sh
        shell: bash

  test-parse-widgets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux

      - name: Run parse widgets tests
        run: bash tests/test_parse_widgets.sh
        shell: bash

  test-set-widget-options:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux

      - name: Run widget options tests
        run: bash tests/test_set_widget_options.sh
        shell: bash
